'use client'

import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Inter, Outfit } from 'next/font/google'
import { FaPaperPlane, FaCheckCircle } from 'react-icons/fa'
import AuthNavbar from '../../components/AuthNavbar'
import Footer from '../../components/Footer'
import { useTheme } from '../../context/ThemeContext'

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

// Renders an animated glowing background blob that adapts to dark/light theme
function SectionGlow({ position = "left" }) {
  const { isDark } = useTheme();
  return (
    <motion.div
      animate={{
        scale: [1, 1.05, 1],
        opacity: [0.08, 0.18, 0.08],
        transition: { duration: 10, repeat: Infinity, ease: "easeInOut" },
      }}
      className={`absolute ${position === "left" ? "-left-40 top-20" : "-right-40 top-40"} h-[450px] w-[450px] rounded-full blur-[140px] ${
        isDark ? "bg-blue-500/10" : "bg-blue-100/70"
      } pointer-events-none -z-10`}
    />
  );
}

// Background gradient mesh matching Vicinity's aesthetics
const GridBackground = () => (
  <div className="absolute inset-0 overflow-hidden -z-20 pointer-events-none bg-white dark:bg-[#081120] transition-colors duration-300">
    <div className="absolute inset-0 bg-gradient-to-b from-white via-slate-50 to-blue-50/30 dark:bg-[#081120]" />
    <div className="absolute top-0 left-1/4 -translate-x-1/2 w-[1000px] h-[600px] bg-blue-200/50 dark:bg-blue-500/10 blur-[130px] rounded-full" />
    <div className="absolute bottom-0 right-1/4 w-[1000px] h-[600px] bg-indigo-100/50 dark:bg-indigo-500/10 blur-[130px] rounded-full" />
  </div>
)

export default function HelpPage() {
  const [contactSubmitted, setContactSubmitted] = useState(false)
  const [contactName, setContactName] = useState('')
  const [contactEmail, setContactEmail] = useState('')
  const [contactMessage, setContactMessage] = useState('')

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (contactName && contactEmail && contactMessage) {
      setContactSubmitted(true)
      setContactName('')
      setContactEmail('')
      setContactMessage('')
    }
  }

  const guideItems = [
    {
      title: "1. Discovering Local Businesses",
      desc: "Browse business listings by category or map location. You can view operating hours, customer reviews, photo galleries, and check out any exclusive local deals published by business owners."
    },
    {
      title: "2. AI Search Capabilities",
      desc: "Instead of searching strictly for keyword matches, our AI model parses semantic intent. If you search for 'a quiet spot to read with coffee', the search engine filters for relaxing local cafes based on actual community reviews and business metadata."
    },
    {
      title: "3. Direct Messaging System",
      desc: "Authenticated users can message business owners directly. Navigate to any business profile and click 'Message'. Conversations are stored inside your user dashboard for easy management. Business owners are notified instantly."
    },
    {
      title: "4. Review Verification & Trust",
      desc: "All reviews are generated by authenticated community members. Businesses cannot pay to remove or manipulate reviews. If you see suspicious activity, flag it for moderator review."
    },
    {
      title: "5. For Business Owners",
      desc: "Creating a business account is simple. Once verified, claim or add your business profile from the business dashboard. You can post real-time deals to attract locals, upload high-res photos, and respond to customer reviews."
    }
  ]

  return (
    <main
      className={`${inter.variable} ${outfit.variable} relative min-h-screen overflow-x-hidden bg-transparent text-slate-900 transition-colors duration-300 dark:text-white flex flex-col`}
      style={{ fontFamily: "var(--font-inter)" }}
    >
      <GridBackground />
      <SectionGlow position="left" />
      <SectionGlow position="right" />
      <AuthNavbar homeText="Back Home" />

      {/* Simplified Hero Section */}
      <div className="relative pt-40 pb-12 px-6 text-center max-w-3xl mx-auto w-full">
        <h1 className="font-[var(--font-outfit)] text-4xl md:text-5xl font-black tracking-tight text-slate-900 dark:text-white">
          Help Guide
        </h1>
        <p className="mt-4 text-sm leading-relaxed text-slate-500 dark:text-slate-400 font-light">
          A simple guide on how to search, review, and connect on Vicinity.
        </p>
      </div>

      {/* Guides list */}
      <div className="max-w-3xl mx-auto px-6 w-full pb-12 relative z-10 space-y-6">
        {guideItems.map((item) => (
          <div 
            key={item.title}
            className="bg-white/80 dark:bg-[#0d1424]/90 border border-blue-500/10 dark:border-white/10 rounded-2xl p-6 shadow-sm"
          >
            <h3 className="font-bold text-base font-[var(--font-outfit)] text-slate-800 dark:text-white mb-2">
              {item.title}
            </h3>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-light">
              {item.desc}
            </p>
          </div>
        ))}
      </div>

      {/* Simple Contact Form Section */}
      <section id="contact" className="scroll-mt-32 max-w-3xl mx-auto px-6 w-full pb-24 relative z-10">
        <div className="bg-white/80 dark:bg-[#0d1424]/90 border border-blue-500/10 dark:border-white/10 rounded-2xl p-8 shadow-sm">
          <h2 className="text-xl font-bold font-[var(--font-outfit)] text-slate-800 dark:text-white mb-2 text-center">
            Contact Support
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mb-6 text-center font-light">
            Send us a message and our support team will get back to you within 24 hours.
          </p>

          {contactSubmitted ? (
            <div className="text-center py-6 flex flex-col items-center">
              <FaCheckCircle className="text-emerald-500 text-3xl mb-3" />
              <h3 className="text-sm font-bold font-[var(--font-outfit)] text-slate-800 dark:text-white">Message Sent!</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 font-light">
                Thank you. We have received your query.
              </p>
            </div>
          ) : (
            <form onSubmit={handleContactSubmit} className="space-y-4">
              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                    Your Name
                  </label>
                  <input 
                    type="text" 
                    required
                    value={contactName}
                    onChange={(e) => setContactName(e.target.value)}
                    placeholder="John Doe"
                    className="w-full px-4 py-2.5 bg-white dark:bg-[#081120]/45 border border-blue-500/15 dark:border-white/10 rounded-xl text-xs text-slate-900 dark:text-white outline-none focus:border-blue-500 dark:focus:border-blue-400 transition-all"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                    Email Address
                  </label>
                  <input 
                    type="email" 
                    required
                    value={contactEmail}
                    onChange={(e) => setContactEmail(e.target.value)}
                    placeholder="john@example.com"
                    className="w-full px-4 py-2.5 bg-white dark:bg-[#081120]/45 border border-blue-500/15 dark:border-white/10 rounded-xl text-xs text-slate-900 dark:text-white outline-none focus:border-blue-500 dark:focus:border-blue-400 transition-all"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                  Message
                </label>
                <textarea 
                  required
                  rows={4}
                  value={contactMessage}
                  onChange={(e) => setContactMessage(e.target.value)}
                  placeholder="How can we help you?"
                  className="w-full px-4 py-2.5 bg-white dark:bg-[#081120]/45 border border-blue-500/15 dark:border-white/10 rounded-xl text-xs text-slate-900 dark:text-white outline-none focus:border-blue-500 dark:focus:border-blue-400 transition-all resize-none"
                />
              </div>

              <div className="flex justify-center pt-2">
                <button 
                  type="submit"
                  className="inline-flex items-center gap-2 px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl shadow-md transition-all hover:scale-[1.02]"
                >
                  Send Message <FaPaperPlane className="text-[10px]" />
                </button>
              </div>
            </form>
          )}
        </div>
      </section>

      <Footer />
    </main>
  )
}
